updates

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -1,8 +1,20 @@
-#!/bin/bash
-# don't commit to master!
+#!/usr/bin/env bash
+# File generated by pre-commit: https://pre-commit.com
+# ID: 138fd403232d2ddd5efb44317e38bf03
 
-if [[ $(git rev-parse --abbrev-ref HEAD) == 'master' ]] || [[ $(git rev-parse --abbrev-ref HEAD) == 'main' ]]; then
-	echo "Don't commit to main dummy"
-	echo "If you really must commit to main then run this command again with -n to skip the hook"
-	exit 1
+# start templated
+INSTALL_PYTHON=/home/cosmic-charlie/.cache/pre-commit-zipapp/QQilD7wlVmDjE2J87CkXuEuSppeB5fQ4PNiEC4yV9IY/python
+ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit --skip-on-missing-config)
+# end templated
+
+HERE="$(cd "$(dirname "$0")" && pwd)"
+ARGS+=(--hook-dir "$HERE" -- "$@")
+
+if [ -x "$INSTALL_PYTHON" ]; then
+    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
+elif command -v pre-commit > /dev/null; then
+    exec pre-commit "${ARGS[@]}"
+else
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
+    exit 1
 fi
